FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:260 in lock_release(): assertion `lock_held_by_current_thread(lock)' failed.
Call stack: 0x800421380e 0x800420a29f 0x80042184aa 0x8004207619
Translation of call stack:
0x000000800421380e: debug_panic (lib/kernel/debug.c:32)
0x000000800420a29f: lock_release (threads/synch.c:262)
0x00000080042184aa: a_thread_func (tests/threads/priority-donate-multiple2.c:72)
0x0000008004207619: kernel_thread (threads/thread.c:576)
